[package]
name = "functor-examples"
version = "0.1.0"
edition = "2021"

[lib]
name = "pong"
path = "examples/Pong/Pong.rs"
crate-type = ["cdylib"]

[[bin]]
name = "pong"
path = "examples/Pong/Pong.rs"

[dependencies]
fable_library_rust = { path = "./fable_modules/fable-library-rust" }
functor_runtime_desktop = { path = "./runtime/functor-runtime-desktop" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"

[profile.release]
codegen-units = 1
lto = true
