[workspace]
resolver = "1"

members = [
    "runtime/functor-runtime-common",
    "runtime/functor-runtime-desktop",
    "runtime/functor-runtime-web",
    "src",
    "examples/Pong/build-native",
    "examples/Pong/build-wasm",
]