// GENERATED by functor import — do not edit; rerun after changing assets
// files: ["bumps-normal.png","gunshot.wav","shark.glb","water-loop.wav","wind-loop.wav"]
// Typed asset constants: pass Assets.<name> where an asset goes; clips via Assets.<name>Clips.<clip>; joints via Assets.<name>Joints.<joint>

type Clip = { name: string, duration: float }

// Models.
let shark = Asset.model("shark.glb")

type SharkClips = {
  bite: Clip,
  circling: Clip,
  swimming: Clip,
}

let sharkClips: SharkClips = {
  bite: { name: "bite", duration: 1.0 },
  circling: { name: "circling", duration: 31.9667 },
  swimming: { name: "swimming", duration: 1.9667 },
}

type SharkJoints = {
  backFinB1_23: string,
  backFinB2_24: string,
  backFinB3_25: string,
  backFinT1_20: string,
  backFinT2_21: string,
  backFinT3_22: string,
  center_upper_Lip_10: string,
  dorsalFin1_26: string,
  dorsalFin2_27: string,
  dorsalFin3_28: string,
  head_5: string,
  jaw_6: string,
  l_Eye_7: string,
  l_Fin1_29: string,
  l_Fin2_30: string,
  l_Fin3_31: string,
  l_upper_Lip_11: string,
  r_Eye_8: string,
  r_Fin1_32: string,
  r_Fin2_33: string,
  r_Fin3_34: string,
  r_upper_Lip_9: string,
  rootNode_0: string,
  spine1_13: string,
  spine2_14: string,
  spine3_15: string,
  spine4_16: string,
  spine5_17: string,
  spine6_18: string,
  spine7_19: string,
  upper_Teeth_12: string,
  shark_root_4: string,
  skeletal_3: string,
}

let sharkJoints: SharkJoints = {
  backFinB1_23: "BackFinB1.23",
  backFinB2_24: "BackFinB2.24",
  backFinB3_25: "BackFinB3.25",
  backFinT1_20: "BackFinT1.20",
  backFinT2_21: "BackFinT2.21",
  backFinT3_22: "BackFinT3.22",
  center_upper_Lip_10: "Center_upper_Lip.10",
  dorsalFin1_26: "DorsalFin1.26",
  dorsalFin2_27: "DorsalFin2.27",
  dorsalFin3_28: "DorsalFin3.28",
  head_5: "Head.5",
  jaw_6: "Jaw.6",
  l_Eye_7: "L_Eye.7",
  l_Fin1_29: "L_Fin1.29",
  l_Fin2_30: "L_Fin2.30",
  l_Fin3_31: "L_Fin3.31",
  l_upper_Lip_11: "L_upper_Lip.11",
  r_Eye_8: "R_Eye.8",
  r_Fin1_32: "R_Fin1.32",
  r_Fin2_33: "R_Fin2.33",
  r_Fin3_34: "R_Fin3.34",
  r_upper_Lip_9: "R_upper_Lip.9",
  rootNode_0: "RootNode.0",
  spine1_13: "Spine1.13",
  spine2_14: "Spine2.14",
  spine3_15: "Spine3.15",
  spine4_16: "Spine4.16",
  spine5_17: "Spine5.17",
  spine6_18: "Spine6.18",
  spine7_19: "Spine7.19",
  upper_Teeth_12: "Upper_Teeth.12",
  shark_root_4: "shark_root.4",
  skeletal_3: "skeletal.3",
}

// Textures.
let bumps_normal = Asset.texture("bumps-normal.png")

// Sounds.
let gunshot = Asset.sound("gunshot.wav")
let water_loop = Asset.sound("water-loop.wav")
let wind_loop = Asset.sound("wind-loop.wav")
