[package]
name = "functor-cli"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "functor"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.6", features = ["derive"] }
colored = "2.1.0"
serde_json = "1.0.117"
tokio = { version = "1", features = ["full"] }
libloading = "0.8.3"
