// GENERATED by functor import — do not edit; rerun after changing assets
// files: ["vr_glove_model.glb"]
// Typed asset constants: pass Assets.<name> where an asset goes; clips via Assets.<name>Clips.<clip>

// Models.
let vr_glove_model = Asset.model("vr_glove_model.glb")
