//! Structured API documentation generated from Functor's embedded `.funi`
//! prelude.

use functor_lang::ast::Item;
use functor_lang::{docs::public_doc_comment_in_source, line_col, parse_interface, Span};
use serde::Serialize;
use std::fmt;
use std::io;
use std::path::Path;

/// The versioned, presentation-neutral API reference consumed by the website
/// and the Markdown renderer.
#[derive(Debug, Serialize)]
pub struct ApiReference {
    pub schema_version: u32,
    pub modules: Vec<ApiModule>,
}

#[derive(Debug, Serialize)]
pub struct ApiModule {
    pub name: String,
    pub docs: Option<String>,
    pub items: Vec<ApiItem>,
}

#[derive(Debug, Serialize)]
pub struct ApiItem {
    pub name: String,
    pub qualified_name: String,
    pub kind: ApiItemKind,
    pub declaration: String,
    pub docs: Option<String>,
}

#[derive(Clone, Copy, Debug, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum ApiItemKind {
    Type,
    Value,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum OutputFormat {
    Markdown,
    Json,
}

#[derive(Debug)]
pub struct GenerateError {
    module: String,
    line: usize,
    col: usize,
    message: String,
}

impl fmt::Display for GenerateError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "{}.funi:{}:{}: {}",
            self.module, self.line, self.col, self.message
        )
    }
}

impl std::error::Error for GenerateError {}

/// Generate the engine API from the exact prelude sources embedded in every
/// Functor runtime and editor.
pub fn generate() -> Result<ApiReference, GenerateError> {
    generate_from_modules(functor_prelude::modules())
}

/// Generate a reference from `(module name, .funi source)` pairs.
pub fn generate_from_modules(
    modules: impl IntoIterator<Item = (String, String)>,
) -> Result<ApiReference, GenerateError> {
    let modules = modules
        .into_iter()
        .map(|(name, source)| extract_module(name, source))
        .collect::<Result<Vec<_>, _>>()?;
    Ok(ApiReference {
        schema_version: 1,
        modules,
    })
}

pub fn render(format: OutputFormat) -> Result<String, GenerateError> {
    let reference = generate()?;
    Ok(match format {
        OutputFormat::Markdown => render_markdown(&reference),
        OutputFormat::Json => {
            let mut json =
                serde_json::to_string_pretty(&reference).expect("API reference is serializable");
            json.push('\n');
            json
        }
    })
}

/// Write generated output, creating a non-empty parent directory when needed.
pub fn write_file(path: &Path, contents: &str) -> io::Result<()> {
    if let Some(parent) = path
        .parent()
        .filter(|parent| !parent.as_os_str().is_empty())
    {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, contents)
}

/// Whether a generated file is current. Git may check text files out with
/// CRLF on Windows, so freshness is intentionally line-ending agnostic.
pub fn file_is_current(path: &Path, generated: &str) -> io::Result<bool> {
    let existing = std::fs::read_to_string(path)?;
    Ok(existing == generated || existing.replace("\r\n", "\n") == generated)
}

pub fn render_markdown(reference: &ApiReference) -> String {
    let mut out = String::from(
        "<!-- Generated by `npm run generate:docs`; do not edit by hand. -->\n\n\
         # Functor API reference\n\n\
         This reference is generated from the `.funi` interface files embedded in Functor.\n",
    );
    for module in &reference.modules {
        out.push_str("\n## ");
        out.push_str(&module.name);
        out.push('\n');
        if let Some(docs) = &module.docs {
            out.push('\n');
            out.push_str(docs);
            out.push('\n');
        }
        for item in &module.items {
            out.push_str("\n### `");
            out.push_str(&item.qualified_name);
            out.push_str("`\n\n```functor\n");
            out.push_str(&item.declaration);
            out.push_str("\n```\n");
            if let Some(docs) = &item.docs {
                out.push('\n');
                out.push_str(docs);
                out.push('\n');
            }
        }
    }
    out
}

fn extract_module(name: String, source: String) -> Result<ApiModule, GenerateError> {
    let program = parse_interface(&source).map_err(|error| {
        let (line, col) = line_col(&source, error.span.start);
        GenerateError {
            module: name.clone(),
            line,
            col,
            message: error.message,
        }
    })?;
    let mut items = Vec::new();
    for item in program.items {
        let (item_name, kind, span) = match item {
            Item::Type(decl) => (decl.name, ApiItemKind::Type, decl.span),
            Item::Sig(decl) => (decl.name, ApiItemKind::Value, decl.span),
            Item::Let(_) | Item::Open(_) | Item::Expect(_) => continue,
        };
        let declaration = declaration_at(&source, span).ok_or_else(|| GenerateError {
            module: name.clone(),
            line: 1,
            col: 1,
            message: format!("invalid source span for `{item_name}`"),
        })?;
        items.push(ApiItem {
            qualified_name: format!("{name}.{item_name}"),
            name: item_name,
            kind,
            declaration,
            docs: public_doc_comment_in_source(&source, span),
        });
    }
    Ok(ApiModule {
        name,
        docs: module_doc(&source),
        items,
    })
}

fn declaration_at(source: &str, span: Span) -> Option<String> {
    source
        .get(span.start..span.end)
        .map(|text| text.trim().to_string())
}

fn module_doc(source: &str) -> Option<String> {
    let mut lines = Vec::new();
    for line in source.lines() {
        let trimmed = line.trim_start();
        if let Some(rest) = trimmed.strip_prefix("//!") {
            lines.push(rest.strip_prefix(' ').unwrap_or(rest));
        } else if trimmed.is_empty() && !lines.is_empty() {
            lines.push("");
        } else if lines.is_empty() && trimmed.is_empty() {
            continue;
        } else {
            break;
        }
    }
    while lines.last().is_some_and(|line| line.is_empty()) {
        lines.pop();
    }
    (!lines.is_empty()).then(|| lines.join("\n"))
}

#[cfg(test)]
mod tests {
    use super::{generate, generate_from_modules, render_markdown, ApiItemKind};

    #[test]
    fn extracts_module_and_item_docs_with_exact_declarations() {
        let source = "//! Widgets for tests.\n\
                      \n\
                      /// An opaque widget.\n\
                      type t\n\
                      \n\
                      /// Make one.\n\
                      let make : (float) => t\n";
        let reference =
            generate_from_modules([("Widget".to_string(), source.to_string())]).unwrap();
        let module = &reference.modules[0];
        assert_eq!(module.docs.as_deref(), Some("Widgets for tests."));
        assert_eq!(module.items.len(), 2);
        assert!(matches!(module.items[0].kind, ApiItemKind::Type));
        assert_eq!(module.items[1].qualified_name, "Widget.make");
        assert_eq!(module.items[1].declaration, "let make : (float) => t");
        assert_eq!(module.items[1].docs.as_deref(), Some("Make one."));

        let markdown = render_markdown(&reference);
        assert!(markdown.contains("## Widget"));
        assert!(markdown.contains("### `Widget.make`"));
    }

    #[test]
    fn embedded_prelude_is_a_complete_parseable_surface() {
        let reference = generate().unwrap();
        assert_eq!(reference.modules.len(), 23);
        assert_eq!(
            reference
                .modules
                .iter()
                .flat_map(|module| &module.items)
                .count(),
            194
        );
        assert!(reference
            .modules
            .iter()
            .any(|module| module.name == "Scene"));
    }

    #[test]
    fn freshness_accepts_windows_line_endings() {
        let path = std::env::temp_dir().join(format!("functor-docgen-crlf-{}", std::process::id()));
        std::fs::write(&path, "one\r\ntwo\r\n").unwrap();
        assert!(super::file_is_current(&path, "one\ntwo\n").unwrap());
        let _ = std::fs::remove_file(path);
    }
}
