[package]
name = "functor-lib"
version = "0.1.0"
edition = "2021"

[lib]
path = "Functor.Game/Platform.rs"

[dependencies]
functor_runtime_common = { path = "./../runtime/functor-runtime-common" }
fable_library_rust = { path = "./../fable_modules/fable-library-rust" }