//! Typed asset-manifest codegen — the pure core of `functor import`
//! (Track B.2 of the asset revamp).
//!
//! Turns a scanned project's assets into the generated `assets.fun` module:
//! one branded constant per asset (`let xbot = Asset.model("Xbot.glb")`), plus
//! declared clip-record constants per animated model
//! (`Assets.xbotClips.walk.name` — a typo is a check-time error instead of a
//! silently-bind-posed `Anim.clip("wlak")`). The generated file is meant to be
//! CHECKED IN: it typechecks without the binary assets present (models are
//! fetched, not committed), and `run`/`build` regenerate it when assets change.
//!
//! This module is deliberately IO-free (names in, source text out) and lives
//! in the shared crate rather than the CLI so future tooling — the wasm build
//! the browser IDE will use — generates byte-identical text. The CLI owns
//! scanning, model inspection, and file IO.
//!
//! Caveat of the nominal design: record literals resolve by field-name set, so
//! a game (or sibling module) declaring its own record type with the same
//! field set as `Clip` or a generated `<Model>Clips` makes those literals
//! ambiguous — a loud load error ("ambiguous record literal … annotate") fixed
//! by renaming a field of the user type.

/// The marker prefix of every generated manifest's first line — how a rerun
/// (and the staleness check) distinguishes generated output from a
/// hand-written `assets.fun`. A PREFIX, not the whole line, so older
/// generated files (whose header text differed) still count as generated.
pub const GENERATED_MARKER: &str = "// GENERATED by functor import";

/// One scanned model's contribution: its file name (as the constructor arg,
/// e.g. `"Xbot.glb"`) and its `(clip name, duration seconds)` pairs.
pub struct ModelEntry {
    pub file: String,
    pub clips: Vec<(String, f32)>,
}

/// Everything the generator needs: the scanned assets by kind. File names are
/// project-dir-relative (the scan is non-recursive, so today they are
/// basenames); the generator sorts each kind, so input order is irrelevant.
#[derive(Default)]
pub struct ManifestInput {
    pub models: Vec<ModelEntry>,
    pub textures: Vec<String>,
    pub sounds: Vec<String>,
}

/// Whether `source` is a generated manifest (vs a hand-written file a rerun
/// must leave alone).
pub fn is_generated(source: &str) -> bool {
    source.starts_with(GENERATED_MARKER)
}

/// The `// files:` inventory of a generated manifest — the sorted file names
/// it was generated from (a JSON array, so any legal filename round-trips),
/// used by the staleness check to detect ADDED assets robustly (a file copied
/// with an old mtime has nothing else to give it away). `None` for
/// hand-written files, older generated formats without the line, and
/// malformed lines — the staleness check treats `None` as "hands off"
/// (explicit `functor import` migrates legacy formats).
pub fn listed_files(source: &str) -> Option<Vec<String>> {
    source.lines().take(3).find_map(|line| {
        line.strip_prefix("// files: ")
            .and_then(|rest| serde_json::from_str::<Vec<String>>(rest).ok())
    })
}

/// The pure generator: scanned assets in, `assets.fun` source out. Returns
/// `None` when there are no assets at all (nothing to write; the caller
/// removes a previously generated file so stale constants can't linger).
///
/// Layout, deterministic by construction (kinds grouped, each sorted by file
/// name, identifier collisions disambiguated in that order — no hash-map
/// iteration order can leak into the text):
///
/// ```functor
/// // Models.
/// let xbot = Asset.model("Xbot.glb")
/// type XbotClips = { walk: Clip, … }     // per distinct clip-field set
/// let xbotClips = { walk: { name: "walk", duration: 0.9667 }, … }
/// // Textures.
/// let dirt = Asset.texture("dirt.png")
/// // Sounds.
/// let gunshot = Asset.sound("gunshot.wav")
/// ```
///
/// Models whose clips are exactly `{name, duration}` would collide with the
/// `Clip` type itself (nominal literal resolution) — their ASSET constant is
/// still emitted, only the clips record is dropped (the caller warns).
/// Duplicate clip names keep only the first (document-order) clip — the one
/// `Anim.clip`'s first-match lookup actually plays.
pub fn generate(input: &ManifestInput) -> Option<String> {
    let mut models: Vec<&ModelEntry> = input.models.iter().collect();
    let mut textures: Vec<&String> = input.textures.iter().collect();
    let mut sounds: Vec<&String> = input.sounds.iter().collect();
    if models.is_empty() && textures.is_empty() && sounds.is_empty() {
        return None;
    }
    models.sort_by(|a, b| a.file.cmp(&b.file));
    textures.sort();
    sounds.sort();

    let mut files: Vec<&str> = models.iter().map(|m| m.file.as_str()).collect();
    files.extend(textures.iter().map(|t| t.as_str()));
    files.extend(sounds.iter().map(|s| s.as_str()));
    files.sort_unstable();

    let mut out = String::new();
    out.push_str(GENERATED_MARKER);
    out.push_str(" — do not edit; rerun after changing assets\n");
    // JSON so any filename (commas, even newlines — escaped) stays one
    // parseable comment line.
    out.push_str(&format!(
        "// files: {}\n",
        serde_json::to_string(&files).expect("string arrays serialize")
    ));
    out.push_str(
        "// Typed asset constants: pass Assets.<name> where an asset goes; \
clips via Assets.<name>Clips.<clip>\n",
    );

    let any_clips = models
        .iter()
        .any(|m| !m.clips.is_empty() && !shadows_clip_type(&m.clips));
    if any_clips {
        out.push_str("\ntype Clip = { name: string, duration: float }\n");
    }

    // ONE identifier space across every generated `let` (model stems, clip
    // records, textures, sounds): a `hero.glb` + `hero.png` pair collides on
    // `hero` and the second claimant gets `hero_2`, deterministically.
    let mut idents = UniqueIdents::new();
    // One declared type per distinct clip-field set (two same-shaped
    // declarations would make every matching literal ambiguous), named after
    // the first (sorted) model that has it.
    let mut declared_field_sets: std::collections::HashSet<Vec<String>> =
        std::collections::HashSet::new();

    if !models.is_empty() {
        out.push_str("\n// Models.\n");
    }
    for model in &models {
        let ident = idents.claim(stem(&model.file));
        out.push_str(&format!(
            "let {} = Asset.model(\"{}\")\n",
            ident,
            escape_string(&model.file)
        ));
        if model.clips.is_empty() || shadows_clip_type(&model.clips) {
            continue;
        }
        let clips_ident = idents.claim(&format!("{ident}Clips"));
        let fields = clip_fields(&model.clips);

        // Key on the SORTED field set: nominal resolution matches by set, so
        // two models whose fields order differently must still share one type.
        let mut field_names: Vec<String> = fields.iter().map(|(f, _, _)| f.clone()).collect();
        field_names.sort();
        if declared_field_sets.insert(field_names) {
            out.push_str(&format!("\ntype {} = {{\n", capitalize(&clips_ident)));
            for (field, _, _) in &fields {
                out.push_str(&format!("  {}: Clip,\n", field));
            }
            out.push_str("}\n");
        }

        out.push_str(&format!("\nlet {} = {{\n", clips_ident));
        for (field, name, duration) in &fields {
            out.push_str(&format!(
                "  {}: {{ name: \"{}\", duration: {} }},\n",
                field,
                escape_string(name),
                format_float(*duration),
            ));
        }
        out.push_str("}\n");
    }

    if !textures.is_empty() {
        out.push_str("\n// Textures.\n");
        for file in &textures {
            let ident = idents.claim(stem(file));
            out.push_str(&format!(
                "let {} = Asset.texture(\"{}\")\n",
                ident,
                escape_string(file)
            ));
        }
    }

    if !sounds.is_empty() {
        out.push_str("\n// Sounds.\n");
        for file in &sounds {
            let ident = idents.claim(stem(file));
            out.push_str(&format!(
                "let {} = Asset.sound(\"{}\")\n",
                ident,
                escape_string(file)
            ));
        }
    }

    Some(out)
}

/// The file name without its final extension (`"Xbot.glb"` → `"Xbot"`) — the
/// raw material for the constant's identifier.
fn stem(file: &str) -> &str {
    file.rsplit_once('.').map(|(s, _)| s).unwrap_or(file)
}

/// Clip names appearing more than once in a model. `Anim.clip` selects by
/// name (first match), so later duplicates are unaddressable — the generator
/// keeps only the first; the caller should warn with these.
pub fn duplicate_clip_names(clips: &[(String, f32)]) -> Vec<String> {
    let mut seen = std::collections::HashSet::new();
    let mut dups = Vec::new();
    for (name, _) in clips {
        if !seen.insert(name) && !dups.contains(name) {
            dups.push(name.clone());
        }
    }
    dups
}

/// The sanitized clip fields (`(field ident, clip name, duration)`) of one
/// model, sorted by original clip name with collisions disambiguated in that
/// order. Duplicate clip NAMES keep only the first (document-order) clip.
fn clip_fields(clips: &[(String, f32)]) -> Vec<(String, String, f32)> {
    let mut seen = std::collections::HashSet::new();
    let mut clips: Vec<&(String, f32)> = clips
        .iter()
        .filter(|(name, _)| seen.insert(name.clone()))
        .collect();
    clips.sort_by(|a, b| a.0.cmp(&b.0));
    let mut idents = UniqueIdents::new();
    clips
        .into_iter()
        .map(|(name, duration)| (idents.claim(name), name.clone(), *duration))
        .collect()
}

/// True when a model's sanitized clip fields are exactly `{name, duration}` —
/// the same field set as the `Clip` record itself. Record literals resolve
/// nominally by field NAMES, so such a model's record would collide with
/// `Clip` and fail the typecheck; its clips are dropped (the caller warns).
pub fn shadows_clip_type(clips: &[(String, f32)]) -> bool {
    let mut fields: Vec<String> = clip_fields(clips).into_iter().map(|(f, _, _)| f).collect();
    fields.sort();
    fields == ["duration", "name"]
}

/// Uppercase the first ASCII letter (idents start lowercase after
/// sanitizing, so this is collision-free across distinct idents).
fn capitalize(s: &str) -> String {
    let mut out = s.to_string();
    if let Some(first) = out.chars().next() {
        if first.is_ascii_lowercase() {
            out.replace_range(..1, &first.to_ascii_uppercase().to_string());
        }
    }
    out
}

/// Words the lexer reserves (the FULL keyword match in
/// `functor-lang/src/lexer.rs`) — a sanitized name landing on one gets a `_`
/// suffix so the generated file still parses (`if.png` must not emit
/// `let if = …`).
const KEYWORDS: &[&str] = &[
    "let", "type", "true", "false", "mut", "with", "in", "match", "if", "then", "else", "not",
];

/// Turn an arbitrary file stem / clip name into a Functor Lang identifier:
/// non-identifier chars (`-`, `.`, spaces, `:`, …) become `_`, the first
/// letter is lowercased (record fields and bindings read lowercase), a
/// leading digit / empty result gets a `_` prefix, and keywords get a `_`
/// suffix.
fn sanitize_ident(raw: &str) -> String {
    let mut s: String = raw
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() || c == '_' { c } else { '_' })
        .collect();
    if let Some(first) = s.chars().next() {
        if first.is_ascii_uppercase() {
            s.replace_range(..1, &first.to_ascii_lowercase().to_string());
        }
    }
    if s.is_empty() || s.starts_with(|c: char| c.is_ascii_digit()) {
        s.insert(0, '_');
    }
    if KEYWORDS.contains(&s.as_str()) {
        s.push('_');
    }
    s
}

/// Sanitizes names and disambiguates collisions deterministically: the first
/// claimant keeps the sanitized name, later ones get `_2`, `_3`, … (skipping
/// suffixes that are themselves already taken).
struct UniqueIdents {
    used: std::collections::HashSet<String>,
}

impl UniqueIdents {
    fn new() -> Self {
        UniqueIdents {
            used: std::collections::HashSet::new(),
        }
    }

    fn claim(&mut self, raw: &str) -> String {
        let base = sanitize_ident(raw);
        let mut candidate = base.clone();
        let mut n = 2;
        while !self.used.insert(candidate.clone()) {
            candidate = format!("{}_{}", base, n);
            n += 1;
        }
        candidate
    }
}

/// Escape a name for a Functor Lang string literal (the language's escapes:
/// `\"` `\\` `\n` `\t`).
fn escape_string(s: &str) -> String {
    s.chars()
        .flat_map(|c| match c {
            '"' => vec!['\\', '"'],
            '\\' => vec!['\\', '\\'],
            '\n' => vec!['\\', 'n'],
            '\t' => vec!['\\', 't'],
            c => vec![c],
        })
        .collect()
}

/// Format a duration as a Functor Lang float literal: fixed 4 decimals (the
/// inspector's display precision), trailing zeros trimmed but at least one
/// decimal kept — `2.24`, `0.9667`, `0.0`. Never scientific notation (the
/// lexer has no exponent form).
fn format_float(f: f32) -> String {
    let s = format!("{:.4}", f);
    let trimmed = s.trim_end_matches('0');
    if trimmed.ends_with('.') {
        format!("{}0", trimmed)
    } else {
        trimmed.to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn models(entries: &[(&str, &[(&str, f32)])]) -> ManifestInput {
        ManifestInput {
            models: entries
                .iter()
                .map(|(file, clips)| ModelEntry {
                    file: file.to_string(),
                    clips: clips
                        .iter()
                        .map(|(n, d)| (n.to_string(), *d))
                        .collect(),
                })
                .collect(),
            ..Default::default()
        }
    }

    #[test]
    fn sanitizes_stems_and_clip_names() {
        assert_eq!(sanitize_ident("Xbot"), "xbot");
        assert_eq!(sanitize_ident("vr_glove_model"), "vr_glove_model");
        assert_eq!(sanitize_ident("sad_pose"), "sad_pose");
        assert_eq!(sanitize_ident("headShake"), "headShake");
        assert_eq!(sanitize_ident("my-model.v2"), "my_model_v2");
        assert_eq!(sanitize_ident("mixamo:rig clip"), "mixamo_rig_clip");
        assert_eq!(sanitize_ident("2fast"), "_2fast");
        assert_eq!(sanitize_ident(""), "_");
        assert_eq!(sanitize_ident("match"), "match_");
    }

    #[test]
    fn full_manifest_golden() {
        let input = ManifestInput {
            models: vec![
                ModelEntry {
                    file: "Xbot.glb".to_string(),
                    clips: vec![("walk".to_string(), 0.9667), ("idle".to_string(), 2.5)],
                },
                ModelEntry {
                    file: "barrel.glb".to_string(),
                    clips: vec![],
                },
            ],
            textures: vec!["wood.png".to_string(), "dirt.png".to_string()],
            sounds: vec!["boom.ogg".to_string()],
        };
        let expected = "\
// GENERATED by functor import — do not edit; rerun after changing assets
// files: [\"Xbot.glb\",\"barrel.glb\",\"boom.ogg\",\"dirt.png\",\"wood.png\"]
// Typed asset constants: pass Assets.<name> where an asset goes; clips via Assets.<name>Clips.<clip>

type Clip = { name: string, duration: float }

// Models.
let xbot = Asset.model(\"Xbot.glb\")

type XbotClips = {
  idle: Clip,
  walk: Clip,
}

let xbotClips = {
  idle: { name: \"idle\", duration: 2.5 },
  walk: { name: \"walk\", duration: 0.9667 },
}
let barrel = Asset.model(\"barrel.glb\")

// Textures.
let dirt = Asset.texture(\"dirt.png\")
let wood = Asset.texture(\"wood.png\")

// Sounds.
let boom = Asset.sound(\"boom.ogg\")
";
        let src = generate(&input).unwrap();
        assert_eq!(src, expected);
        // Byte-identical on a second run, and self-describing.
        assert_eq!(generate(&input).unwrap(), expected);
        assert!(is_generated(&src));
        assert_eq!(
            listed_files(&src).unwrap(),
            vec!["Xbot.glb", "barrel.glb", "boom.ogg", "dirt.png", "wood.png"]
        );
    }

    #[test]
    fn clipless_projects_omit_the_clip_type() {
        let input = ManifestInput {
            textures: vec!["wood.png".to_string()],
            ..Default::default()
        };
        let src = generate(&input).unwrap();
        assert!(!src.contains("type Clip"));
        assert!(src.contains("let wood = Asset.texture(\"wood.png\")"));
    }

    #[test]
    fn empty_input_generates_nothing() {
        assert_eq!(generate(&ManifestInput::default()), None);
    }

    #[test]
    fn cross_kind_ident_collisions_disambiguate() {
        let input = ManifestInput {
            models: vec![ModelEntry {
                file: "hero.glb".to_string(),
                clips: vec![],
            }],
            textures: vec!["hero.png".to_string()],
            sounds: vec!["hero.ogg".to_string()],
        };
        let src = generate(&input).unwrap();
        assert!(src.contains("let hero = Asset.model(\"hero.glb\")"));
        assert!(src.contains("let hero_2 = Asset.texture(\"hero.png\")"));
        assert!(src.contains("let hero_3 = Asset.sound(\"hero.ogg\")"));
    }

    #[test]
    fn collisions_disambiguate_deterministically() {
        let input = models(&[(
            "bot.glb",
            &[("walk", 1.0), ("Walk", 2.0), ("wa-lk", 3.0)][..],
        )]);
        let src = generate(&input).unwrap();
        // Clips sort by ORIGINAL name (Walk < wa-lk < walk), then collide on
        // the sanitized "walk"/"wa_lk": first claimant keeps the name.
        assert!(src.contains("  walk: { name: \"Walk\", duration: 2.0 },"));
        assert!(src.contains("  wa_lk: { name: \"wa-lk\", duration: 3.0 },"));
        assert!(src.contains("  walk_2: { name: \"walk\", duration: 1.0 },"));
    }

    #[test]
    fn zero_clip_models_still_get_asset_constants() {
        let input = models(&[
            ("vr_glove_model.glb", &[][..]),
            ("Xbot.glb", &[("idle", 2.24)][..]),
        ]);
        let src = generate(&input).unwrap();
        assert!(src.contains("let vr_glove_model = Asset.model(\"vr_glove_model.glb\")"));
        assert!(!src.contains("vr_glove_modelClips"));
        assert!(src.contains("let xbot = Asset.model(\"Xbot.glb\")"));
        assert!(src.contains("let xbotClips = {"));
    }

    #[test]
    fn same_shaped_models_share_one_declared_type() {
        // Two models with identical clip fields must NOT declare two
        // same-shaped types (the checker would find the record literals
        // ambiguous) — the second reuses the first's.
        let input = models(&[
            ("xbot.glb", &[("idle", 1.0)][..]),
            ("ybot.glb", &[("idle", 2.0)][..]),
        ]);
        let src = generate(&input).unwrap();
        assert_eq!(src.matches("type XbotClips").count(), 1);
        assert!(!src.contains("type YbotClips"));
        assert!(src.contains("let ybotClips = {"));
    }

    #[test]
    fn same_field_set_in_different_order_still_shares_the_type() {
        // Clip sorting is by ORIGINAL name, so casing can order the same
        // sanitized field set differently per model. The type key must be the
        // sorted SET — emitting two same-shaped types would make every
        // matching literal ambiguous.
        let input = models(&[
            ("abot.glb", &[("Idle", 1.0), ("run", 2.0)][..]),
            ("bbot.glb", &[("idle", 3.0), ("Run", 4.0)][..]),
        ]);
        let src = generate(&input).unwrap();
        assert_eq!(
            src.matches("type ").count(),
            2,
            "Clip + ONE shared model type:\n{src}"
        );
        assert!(src.contains("type AbotClips"));
        assert!(!src.contains("type BbotClips"));
    }

    #[test]
    fn duplicate_clip_names_keep_only_the_first() {
        // Anim.clip plays the FIRST clip with a given name, so a `walk_2`
        // whose .name is still "walk" would be unaddressable — only the
        // first (document-order) duplicate is generated.
        let clips = vec![
            ("walk".to_string(), 1.0),
            ("idle".to_string(), 2.0),
            ("walk".to_string(), 3.0),
        ];
        assert_eq!(duplicate_clip_names(&clips), vec!["walk".to_string()]);
        let input = models(&[("bot.glb", &[("walk", 1.0), ("idle", 2.0), ("walk", 3.0)][..])]);
        let src = generate(&input).unwrap();
        assert!(src.contains("  walk: { name: \"walk\", duration: 1.0 },"));
        assert!(!src.contains("walk_2"));
    }

    #[test]
    fn clip_shadowing_models_keep_the_asset_but_drop_the_clips() {
        // A model whose clips are literally named "name" and "duration" has
        // the same field set as `Clip` itself — nominal literal resolution
        // would collide, so its clips are dropped (the caller warns) while
        // the asset constant survives.
        let shadowing = vec![("name".to_string(), 1.0), ("duration".to_string(), 2.0)];
        assert!(shadows_clip_type(&shadowing));
        assert!(!shadows_clip_type(&[("idle".to_string(), 1.0)]));
        let input = models(&[("weird.glb", &[("name", 1.0), ("duration", 2.0)][..])]);
        let src = generate(&input).unwrap();
        assert!(src.contains("let weird = Asset.model(\"weird.glb\")"));
        assert!(!src.contains("weirdClips"));
        assert!(!src.contains("type Clip"), "no clips -> no Clip type:\n{src}");
    }

    /// Hostile names — keyword stems (`if.png` — the lexer reserves
    /// if/then/else/not too), digits, unicode, quotes, commas, even a
    /// newline — must still yield a manifest that PARSES, with the inventory
    /// round-tripping exactly.
    #[test]
    fn hostile_names_still_parse_and_round_trip() {
        let input = ManifestInput {
            models: vec![ModelEntry {
                file: "2fast.glb".to_string(),
                clips: vec![("else".to_string(), 1.0), ("not".to_string(), 2.0)],
            }],
            textures: vec![
                "if.png".to_string(),
                "then.png".to_string(),
                "a, b.png".to_string(),
                "qu\"ote.png".to_string(),
            ],
            sounds: vec!["weird\nname.ogg".to_string(), "übung.ogg".to_string()],
        };
        let src = generate(&input).unwrap();
        assert!(src.contains("let if_ = Asset.texture(\"if.png\")"), "{src}");
        assert!(src.contains("  else_: { name: \"else\", duration: 1.0 },"));
        functor_lang::parse(&src).expect("hostile names must still generate parseable code");
        let mut expected: Vec<String> = [
            "2fast.glb",
            "if.png",
            "then.png",
            "a, b.png",
            "qu\"ote.png",
            "weird\nname.ogg",
            "übung.ogg",
        ]
        .iter()
        .map(|s| s.to_string())
        .collect();
        expected.sort();
        assert_eq!(listed_files(&src).unwrap(), expected);
    }

    #[test]
    fn old_format_headers_still_count_as_generated() {
        let old = "// GENERATED by functor import — do not edit; rerun after changing models\n\
type Clip = { name: string, duration: float }\n";
        assert!(is_generated(old));
        assert_eq!(listed_files(old), None); // no inventory -> auto-reimport keeps off
        assert!(!is_generated("// my hand-written assets file\n"));
    }

    #[test]
    fn floats_are_plain_literals() {
        assert_eq!(format_float(2.24), "2.24");
        assert_eq!(format_float(0.9667), "0.9667");
        assert_eq!(format_float(2.0), "2.0");
        assert_eq!(format_float(0.0), "0.0");
        // Sub-precision durations round to the fixed grid, never sci-notation.
        assert_eq!(format_float(0.00001), "0.0");
    }

    #[test]
    fn escapes_string_literals() {
        assert_eq!(escape_string("wa\"lk"), "wa\\\"lk");
        assert_eq!(escape_string("a\\b"), "a\\\\b");
        assert_eq!(escape_string("a\nb\tc"), "a\\nb\\tc");
    }
}
