//! Typed asset-manifest codegen — the pure core of `functor import`
//! (Track B.2 of the asset revamp).
//!
//! Turns a scanned project's assets into the generated `assets.fun` module:
//! one branded constant per asset (`let xbot = Asset.model("Xbot.glb")`), plus
//! declared clip- and joint-record constants per model
//! (`Assets.xbotClips.walk.name`, `Assets.xbotJoints.mixamorig_Head`). A typo is
//! a check-time error instead of a silently-bind-posed clip or ignored joint.
//! The generated file is meant to be CHECKED IN: it typechecks without the
//! binary assets present (models are fetched, not committed), and `run`/`build`
//! regenerate it when assets change.
//!
//! This module is deliberately IO-free (names in, source text out) and lives
//! in the shared crate rather than the CLI so future tooling — the wasm build
//! the browser IDE will use — generates byte-identical text. The CLI owns
//! scanning, model inspection, and file IO.
//!
//! Caveat of the nominal design: record literals resolve by field-name set, so
//! a game (or sibling module) declaring its own record type with the same
//! field set as `Clip` or a generated model record can make unannotated user
//! literals ambiguous — a loud load error ("ambiguous record literal …
//! annotate") fixed by annotating the user literal or renaming one of its
//! fields. Generated literals carry explicit annotations, so generated record
//! shapes cannot make the manifest itself ambiguous.

/// The marker prefix of every generated manifest's first line — how a rerun
/// (and the staleness check) distinguishes generated output from a
/// hand-written `assets.fun`. A PREFIX, not the whole line, so older
/// generated files (whose header text differed) still count as generated.
pub const GENERATED_MARKER: &str = "// GENERATED by functor import";

/// One asset's contribution: the NAME its constant derives from (a local
/// file's stem, or a sidecar's `<name>.asset.json` name) and the LOCATOR the
/// constructor receives (a project-relative file name like `"Xbot.glb"`, or a
/// URL for sidecar-declared remote assets).
pub struct AssetEntry {
    pub name: String,
    pub locator: String,
}

/// A model entry additionally carries its `(clip name, duration s)` pairs and
/// exact skeleton joint names.
pub struct ModelEntry {
    pub name: String,
    pub locator: String,
    pub clips: Vec<(String, f32)>,
    pub joints: Vec<String>,
}

/// Everything the generator needs: the scanned assets by kind. The generator
/// sorts each kind by `(name, locator)`, so input order is irrelevant.
#[derive(Default)]
pub struct ManifestInput {
    pub models: Vec<ModelEntry>,
    pub textures: Vec<AssetEntry>,
    pub sounds: Vec<AssetEntry>,
    /// The on-disk files this manifest was generated from — local asset files
    /// AND sidecar `.asset.json` files (not URL targets, which have no mtime).
    /// Becomes the `// files:` inventory the staleness check reads.
    pub files: Vec<String>,
}

/// Whether `source` is a generated manifest (vs a hand-written file a rerun
/// must leave alone).
pub fn is_generated(source: &str) -> bool {
    source.starts_with(GENERATED_MARKER)
}

/// The `// files:` inventory of a generated manifest — the sorted file names
/// it was generated from (a JSON array, so any legal filename round-trips),
/// used by the staleness check to detect ADDED assets robustly (a file copied
/// with an old mtime has nothing else to give it away). `None` for
/// hand-written files, older generated formats without the line, and
/// malformed lines — the staleness check treats `None` as "hands off"
/// (explicit `functor import` migrates legacy formats).
pub fn listed_files(source: &str) -> Option<Vec<String>> {
    source.lines().take(3).find_map(|line| {
        line.strip_prefix("// files: ")
            .and_then(|rest| serde_json::from_str::<Vec<String>>(rest).ok())
    })
}

/// The pure generator: scanned assets in, `assets.fun` source out. Returns
/// `None` when there are no assets at all (nothing to write; the caller
/// removes a previously generated file so stale constants can't linger).
///
/// Layout, deterministic by construction (kinds grouped, each sorted by file
/// name, identifier collisions disambiguated in that order — no hash-map
/// iteration order can leak into the text):
///
/// ```functor
/// // Models.
/// let xbot = Asset.model("Xbot.glb")
/// type XbotClips = { walk: Clip, … }     // per distinct clip-field set
/// let xbotClips: XbotClips = { walk: { name: "walk", duration: 0.9667 }, … }
/// type XbotJoints = { mixamorig_Head: string, … }
/// let xbotJoints: XbotJoints = { mixamorig_Head: "mixamorig:Head", … }
/// // Textures.
/// let dirt = Asset.texture("dirt.png")
/// // Sounds.
/// let gunshot = Asset.sound("gunshot.wav")
/// ```
///
/// Duplicate clip names keep only the first (document-order) clip — the one
/// `Anim.clip`'s first-match lookup actually plays.
pub fn generate(input: &ManifestInput) -> Option<String> {
    let mut models: Vec<&ModelEntry> = input.models.iter().collect();
    let mut textures: Vec<&AssetEntry> = input.textures.iter().collect();
    let mut sounds: Vec<&AssetEntry> = input.sounds.iter().collect();
    if models.is_empty() && textures.is_empty() && sounds.is_empty() {
        return None;
    }
    models.sort_by(|a, b| (&a.name, &a.locator).cmp(&(&b.name, &b.locator)));
    textures.sort_by(|a, b| (&a.name, &a.locator).cmp(&(&b.name, &b.locator)));
    sounds.sort_by(|a, b| (&a.name, &a.locator).cmp(&(&b.name, &b.locator)));

    let mut files: Vec<&str> = input.files.iter().map(|f| f.as_str()).collect();
    files.sort_unstable();

    let mut out = String::new();
    out.push_str(GENERATED_MARKER);
    out.push_str(" — do not edit; rerun after changing assets\n");
    // JSON so any filename (commas, even newlines — escaped) stays one
    // parseable comment line.
    out.push_str(&format!(
        "// files: {}\n",
        serde_json::to_string(&files).expect("string arrays serialize")
    ));
    out.push_str(
        "// Typed asset constants: pass Assets.<name> where an asset goes; \
clips via Assets.<name>Clips.<clip>; joints via Assets.<name>Joints.<joint>\n",
    );

    let any_clips = models.iter().any(|m| !m.clips.is_empty());
    if any_clips {
        out.push_str("\ntype Clip = { name: string, duration: float }\n");
    }

    // ONE identifier space across every generated `let`. Reserve the actual
    // assets first (models, then textures, then sounds) so adding derived
    // `<model>Clips` / `<model>Joints` records never renames an existing asset
    // constant. A `hero.glb` + `hero.png` pair still makes the latter `hero_2`.
    let mut idents = UniqueIdents::new();
    let model_idents: Vec<String> = models
        .iter()
        .map(|model| idents.claim(&model.name))
        .collect();
    let texture_idents: Vec<String> = textures
        .iter()
        .map(|entry| idents.claim(&entry.name))
        .collect();
    let sound_idents: Vec<String> = sounds
        .iter()
        .map(|entry| idents.claim(&entry.name))
        .collect();
    // One declared type per distinct field set within each record family,
    // named after the first (sorted) model that has it. Generated values are
    // explicitly annotated: a clip and joint record may therefore have the
    // same field set while keeping their different field value types.
    let mut declared_clip_field_sets: std::collections::HashMap<Vec<String>, String> =
        std::collections::HashMap::new();
    let mut declared_joint_field_sets: std::collections::HashMap<Vec<String>, String> =
        std::collections::HashMap::new();

    if !models.is_empty() {
        out.push_str("\n// Models.\n");
    }
    for (model, ident) in models.iter().zip(&model_idents) {
        out.push_str(&format!(
            "let {} = Asset.model(\"{}\")\n",
            ident,
            escape_string(&model.locator)
        ));
        if !model.clips.is_empty() {
            let clips_ident = idents.claim(&format!("{ident}Clips"));
            let fields = clip_fields(&model.clips);

            // Key on the SORTED field set: nominal resolution matches by set,
            // so two models whose fields order differently share one type.
            let mut field_names: Vec<String> = fields.iter().map(|(f, _, _)| f.clone()).collect();
            field_names.sort();
            let clips_type = match declared_clip_field_sets.get(&field_names) {
                Some(existing) => existing.clone(),
                None => {
                    let declared = capitalize(&clips_ident);
                    out.push_str(&format!("\ntype {} = {{\n", declared));
                    for (field, _, _) in &fields {
                        out.push_str(&format!("  {}: Clip,\n", field));
                    }
                    out.push_str("}\n");
                    declared_clip_field_sets.insert(field_names, declared.clone());
                    declared
                }
            };

            out.push_str(&format!("\nlet {}: {} = {{\n", clips_ident, clips_type));
            for (field, name, duration) in &fields {
                out.push_str(&format!(
                    "  {}: {{ name: \"{}\", duration: {} }},\n",
                    field,
                    escape_string(name),
                    format_float(*duration),
                ));
            }
            out.push_str("}\n");
        }

        if !model.joints.is_empty() {
            let joints_ident = idents.claim(&format!("{ident}Joints"));
            let fields = joint_fields(&model.joints);
            let mut field_names: Vec<String> =
                fields.iter().map(|(field, _)| field.clone()).collect();
            field_names.sort();
            let joints_type = match declared_joint_field_sets.get(&field_names) {
                Some(existing) => existing.clone(),
                None => {
                    let declared = capitalize(&joints_ident);
                    out.push_str(&format!("\ntype {} = {{\n", declared));
                    for (field, _) in &fields {
                        out.push_str(&format!("  {}: string,\n", field));
                    }
                    out.push_str("}\n");
                    declared_joint_field_sets.insert(field_names, declared.clone());
                    declared
                }
            };

            out.push_str(&format!("\nlet {}: {} = {{\n", joints_ident, joints_type));
            for (field, name) in &fields {
                out.push_str(&format!("  {}: \"{}\",\n", field, escape_string(name),));
            }
            out.push_str("}\n");
        }
    }

    if !textures.is_empty() {
        out.push_str("\n// Textures.\n");
        for (entry, ident) in textures.iter().zip(&texture_idents) {
            out.push_str(&format!(
                "let {} = Asset.texture(\"{}\")\n",
                ident,
                escape_string(&entry.locator)
            ));
        }
    }

    if !sounds.is_empty() {
        out.push_str("\n// Sounds.\n");
        for (entry, ident) in sounds.iter().zip(&sound_idents) {
            out.push_str(&format!(
                "let {} = Asset.sound(\"{}\")\n",
                ident,
                escape_string(&entry.locator)
            ));
        }
    }

    Some(out)
}

/// Clip names appearing more than once in a model. `Anim.clip` selects by
/// name (first match), so later duplicates are unaddressable — the generator
/// keeps only the first; the caller should warn with these.
pub fn duplicate_clip_names(clips: &[(String, f32)]) -> Vec<String> {
    duplicate_names(clips.iter().map(|(name, _)| name.as_str()))
}

/// Joint names appearing more than once in a model. `Anim.rotate` and
/// `Anim.lookAt` select the smallest matching node id while `Anim.mask`
/// selects all matching subtrees; duplicate nodes are not individually
/// name-addressable, so the generator emits one field.
pub fn duplicate_joint_names(joints: &[String]) -> Vec<String> {
    duplicate_names(joints.iter().map(String::as_str))
}

/// Repeated exact names, once each and in the order each first repeats.
fn duplicate_names<'a>(names: impl IntoIterator<Item = &'a str>) -> Vec<String> {
    let mut seen = std::collections::HashSet::new();
    let mut emitted = std::collections::HashSet::new();
    let mut dups = Vec::new();
    for name in names {
        if !seen.insert(name) && emitted.insert(name) {
            dups.push(name.to_string());
        }
    }
    dups
}

/// The sanitized clip fields (`(field ident, clip name, duration)`) of one
/// model, sorted by original clip name with collisions disambiguated in that
/// order. Duplicate clip NAMES keep only the first (document-order) clip.
fn clip_fields(clips: &[(String, f32)]) -> Vec<(String, String, f32)> {
    let mut seen = std::collections::HashSet::new();
    let mut clips: Vec<&(String, f32)> = clips
        .iter()
        .filter(|(name, _)| seen.insert(name.clone()))
        .collect();
    clips.sort_by(|a, b| a.0.cmp(&b.0));
    let mut idents = UniqueIdents::new();
    clips
        .into_iter()
        .map(|(name, duration)| (idents.claim(name), name.clone(), *duration))
        .collect()
}

/// The sanitized joint fields (`(field ident, exact joint name)`) of one
/// model, sorted by original name with collisions disambiguated in that
/// order. Duplicate exact names keep only the first because only one
/// name-based constant can address them.
fn joint_fields(joints: &[String]) -> Vec<(String, String)> {
    let mut seen = std::collections::HashSet::new();
    let mut joints: Vec<&String> = joints.iter().filter(|name| seen.insert(*name)).collect();
    joints.sort();
    let mut idents = UniqueIdents::new();
    joints
        .into_iter()
        .map(|name| (idents.claim(name), name.clone()))
        .collect()
}

/// Uppercase the first ASCII letter (idents start lowercase after
/// sanitizing, so this is collision-free across distinct idents).
fn capitalize(s: &str) -> String {
    let mut out = s.to_string();
    if let Some(first) = out.chars().next() {
        if first.is_ascii_lowercase() {
            out.replace_range(..1, &first.to_ascii_uppercase().to_string());
        }
    }
    out
}

/// Words the lexer reserves (the FULL keyword match in
/// `functor-lang/src/lexer.rs`) — a sanitized name landing on one gets a `_`
/// suffix so the generated file still parses (`if.png` must not emit
/// `let if = …`).
const KEYWORDS: &[&str] = &[
    "let", "type", "true", "false", "mut", "with", "in", "match", "if", "then", "else", "not",
];

/// Turn an arbitrary file stem / clip name into a Functor Lang identifier:
/// non-identifier chars (`-`, `.`, spaces, `:`, …) become `_`, the first
/// letter is lowercased (record fields and bindings read lowercase), a
/// leading digit / empty result gets a `_` prefix, and keywords get a `_`
/// suffix.
fn sanitize_ident(raw: &str) -> String {
    let mut s: String = raw
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() || c == '_' { c } else { '_' })
        .collect();
    if let Some(first) = s.chars().next() {
        if first.is_ascii_uppercase() {
            s.replace_range(..1, &first.to_ascii_lowercase().to_string());
        }
    }
    if s.is_empty() || s.starts_with(|c: char| c.is_ascii_digit()) {
        s.insert(0, '_');
    }
    if KEYWORDS.contains(&s.as_str()) {
        s.push('_');
    }
    s
}

/// Sanitizes names and disambiguates collisions deterministically: the first
/// claimant keeps the sanitized name, later ones get `_2`, `_3`, … (skipping
/// suffixes that are themselves already taken).
struct UniqueIdents {
    used: std::collections::HashSet<String>,
}

impl UniqueIdents {
    fn new() -> Self {
        UniqueIdents {
            used: std::collections::HashSet::new(),
        }
    }

    fn claim(&mut self, raw: &str) -> String {
        let base = sanitize_ident(raw);
        let mut candidate = base.clone();
        let mut n = 2;
        while !self.used.insert(candidate.clone()) {
            candidate = format!("{}_{}", base, n);
            n += 1;
        }
        candidate
    }
}

/// Escape a name for a Functor Lang string literal (the language's escapes:
/// `\"` `\\` `\n` `\t`).
fn escape_string(s: &str) -> String {
    s.chars()
        .flat_map(|c| match c {
            '"' => vec!['\\', '"'],
            '\\' => vec!['\\', '\\'],
            '\n' => vec!['\\', 'n'],
            '\t' => vec!['\\', 't'],
            c => vec![c],
        })
        .collect()
}

/// Format a duration as a Functor Lang float literal: fixed 4 decimals (the
/// inspector's display precision), trailing zeros trimmed but at least one
/// decimal kept — `2.24`, `0.9667`, `0.0`. Never scientific notation (the
/// lexer has no exponent form).
fn format_float(f: f32) -> String {
    let s = format!("{:.4}", f);
    let trimmed = s.trim_end_matches('0');
    if trimmed.ends_with('.') {
        format!("{}0", trimmed)
    } else {
        trimmed.to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A local file's stem — what the CLI passes as an entry's `name`.
    fn stem(file: &str) -> String {
        file.rsplit_once('.')
            .map(|(s, _)| s)
            .unwrap_or(file)
            .to_string()
    }

    fn local(file: &str) -> AssetEntry {
        AssetEntry {
            name: stem(file),
            locator: file.to_string(),
        }
    }

    /// A local-files-only input, `files` derived from the locators (the CLI
    /// does the same for a sidecar-free project).
    fn local_input(
        model_entries: &[(&str, &[(&str, f32)])],
        textures: &[&str],
        sounds: &[&str],
    ) -> ManifestInput {
        let mut files: Vec<String> = model_entries
            .iter()
            .map(|(file, _)| file.to_string())
            .collect();
        files.extend(textures.iter().map(|f| f.to_string()));
        files.extend(sounds.iter().map(|f| f.to_string()));
        ManifestInput {
            models: model_entries
                .iter()
                .map(|(file, clips)| ModelEntry {
                    name: stem(file),
                    locator: file.to_string(),
                    clips: clips.iter().map(|(n, d)| (n.to_string(), *d)).collect(),
                    joints: Vec::new(),
                })
                .collect(),
            textures: textures.iter().map(|f| local(f)).collect(),
            sounds: sounds.iter().map(|f| local(f)).collect(),
            files,
        }
    }

    fn models(entries: &[(&str, &[(&str, f32)])]) -> ManifestInput {
        local_input(entries, &[], &[])
    }

    #[test]
    fn sanitizes_stems_and_clip_names() {
        assert_eq!(sanitize_ident("Xbot"), "xbot");
        assert_eq!(sanitize_ident("vr_glove_model"), "vr_glove_model");
        assert_eq!(sanitize_ident("sad_pose"), "sad_pose");
        assert_eq!(sanitize_ident("headShake"), "headShake");
        assert_eq!(sanitize_ident("my-model.v2"), "my_model_v2");
        assert_eq!(sanitize_ident("mixamo:rig clip"), "mixamo_rig_clip");
        assert_eq!(sanitize_ident("2fast"), "_2fast");
        assert_eq!(sanitize_ident(""), "_");
        assert_eq!(sanitize_ident("match"), "match_");
    }

    #[test]
    fn full_manifest_golden() {
        let input = local_input(
            &[
                ("Xbot.glb", &[("walk", 0.9667), ("idle", 2.5)][..]),
                ("barrel.glb", &[][..]),
            ],
            &["wood.png", "dirt.png"],
            &["boom.ogg"],
        );
        let expected = "\
// GENERATED by functor import — do not edit; rerun after changing assets
// files: [\"Xbot.glb\",\"barrel.glb\",\"boom.ogg\",\"dirt.png\",\"wood.png\"]
// Typed asset constants: pass Assets.<name> where an asset goes; clips via Assets.<name>Clips.<clip>; joints via Assets.<name>Joints.<joint>

type Clip = { name: string, duration: float }

// Models.
let xbot = Asset.model(\"Xbot.glb\")

type XbotClips = {
  idle: Clip,
  walk: Clip,
}

let xbotClips: XbotClips = {
  idle: { name: \"idle\", duration: 2.5 },
  walk: { name: \"walk\", duration: 0.9667 },
}
let barrel = Asset.model(\"barrel.glb\")

// Textures.
let dirt = Asset.texture(\"dirt.png\")
let wood = Asset.texture(\"wood.png\")

// Sounds.
let boom = Asset.sound(\"boom.ogg\")
";
        let src = generate(&input).unwrap();
        assert_eq!(src, expected);
        // Byte-identical on a second run, and self-describing.
        assert_eq!(generate(&input).unwrap(), expected);
        assert!(is_generated(&src));
        assert_eq!(
            listed_files(&src).unwrap(),
            vec!["Xbot.glb", "barrel.glb", "boom.ogg", "dirt.png", "wood.png"]
        );
    }

    #[test]
    fn clipless_projects_omit_the_clip_type() {
        let input = local_input(&[], &["wood.png"], &[]);
        let src = generate(&input).unwrap();
        assert!(!src.contains("type Clip"));
        assert!(src.contains("let wood = Asset.texture(\"wood.png\")"));
    }

    #[test]
    fn empty_input_generates_nothing() {
        assert_eq!(generate(&ManifestInput::default()), None);
    }

    #[test]
    fn cross_kind_ident_collisions_disambiguate() {
        let input = local_input(&[("hero.glb", &[][..])], &["hero.png"], &["hero.ogg"]);
        let src = generate(&input).unwrap();
        assert!(src.contains("let hero = Asset.model(\"hero.glb\")"));
        assert!(src.contains("let hero_2 = Asset.texture(\"hero.png\")"));
        assert!(src.contains("let hero_3 = Asset.sound(\"hero.ogg\")"));
    }

    #[test]
    fn derived_records_never_steal_asset_identifiers() {
        let input = ManifestInput {
            models: vec![ModelEntry {
                name: "hero".to_string(),
                locator: "hero.glb".to_string(),
                clips: vec![("idle".to_string(), 1.0)],
                joints: vec!["head".to_string()],
            }],
            textures: vec![
                AssetEntry {
                    name: "heroClips".to_string(),
                    locator: "heroClips.png".to_string(),
                },
                AssetEntry {
                    name: "heroJoints".to_string(),
                    locator: "heroJoints.png".to_string(),
                },
            ],
            files: vec![
                "hero.glb".to_string(),
                "heroClips.png".to_string(),
                "heroJoints.png".to_string(),
            ],
            ..Default::default()
        };
        let src = generate(&input).unwrap();
        assert!(src.contains("let heroClips = Asset.texture(\"heroClips.png\")"));
        assert!(src.contains("let heroJoints = Asset.texture(\"heroJoints.png\")"));
        assert!(src.contains("let heroClips_2: HeroClips_2 = {"));
        assert!(src.contains("let heroJoints_2: HeroJoints_2 = {"));
    }

    #[test]
    fn collisions_disambiguate_deterministically() {
        let input = models(&[(
            "bot.glb",
            &[("walk", 1.0), ("Walk", 2.0), ("wa-lk", 3.0)][..],
        )]);
        let src = generate(&input).unwrap();
        // Clips sort by ORIGINAL name (Walk < wa-lk < walk), then collide on
        // the sanitized "walk"/"wa_lk": first claimant keeps the name.
        assert!(src.contains("  walk: { name: \"Walk\", duration: 2.0 },"));
        assert!(src.contains("  wa_lk: { name: \"wa-lk\", duration: 3.0 },"));
        assert!(src.contains("  walk_2: { name: \"walk\", duration: 1.0 },"));
    }

    #[test]
    fn joint_names_generate_typed_exact_string_constants() {
        let input = ManifestInput {
            models: vec![ModelEntry {
                name: "Xbot".to_string(),
                locator: "Xbot.glb".to_string(),
                clips: Vec::new(),
                joints: vec![
                    "mixamorig:Head".to_string(),
                    "finger_index_0_r".to_string(),
                    "mixamorig Head".to_string(),
                    "mixamorig:Head".to_string(),
                ],
            }],
            files: vec!["Xbot.glb".to_string()],
            ..Default::default()
        };
        let src = generate(&input).unwrap();
        assert!(src.contains("type XbotJoints = {"));
        assert!(src.contains("  finger_index_0_r: string,"));
        assert!(src.contains("  mixamorig_Head: string,"));
        assert!(src.contains("  mixamorig_Head_2: string,"));
        assert!(src.contains("let xbotJoints: XbotJoints = {"));
        assert!(src.contains("  mixamorig_Head: \"mixamorig Head\","));
        assert!(src.contains("  mixamorig_Head_2: \"mixamorig:Head\","));
        assert_eq!(src.matches("\"mixamorig:Head\"").count(), 1);
        functor_lang::parse(&src).expect("joint constants must generate parseable code");
    }

    #[test]
    fn duplicate_joint_names_report_once_and_generate_once() {
        let joints = vec![
            "head".to_string(),
            "hand".to_string(),
            "head".to_string(),
            "head".to_string(),
        ];
        assert_eq!(duplicate_joint_names(&joints), vec!["head".to_string()]);
        assert_eq!(
            joint_fields(&joints),
            vec![
                ("hand".to_string(), "hand".to_string()),
                ("head".to_string(), "head".to_string()),
            ]
        );
    }

    #[test]
    fn clip_and_joint_records_with_the_same_shape_are_annotated() {
        let input = ManifestInput {
            models: vec![ModelEntry {
                name: "bot".to_string(),
                locator: "bot.glb".to_string(),
                clips: vec![("head".to_string(), 1.0)],
                joints: vec!["head".to_string()],
            }],
            files: vec!["bot.glb".to_string()],
            ..Default::default()
        };
        let src = generate(&input).unwrap();
        assert!(src.contains("let botClips: BotClips = {"));
        assert!(src.contains("let botJoints: BotJoints = {"));
        let parsed = functor_lang::parse(&src).expect("annotated same-shaped records must parse");
        let module = functor_lang::lower(parsed).expect("generated names must lower");
        let diagnostics = functor_lang::check(&module);
        assert!(
            diagnostics.is_empty(),
            "annotated clip/joint records must typecheck: {diagnostics:#?}\n{src}"
        );
    }

    #[test]
    fn zero_clip_models_still_get_asset_constants() {
        let input = models(&[
            ("vr_glove_model.glb", &[][..]),
            ("Xbot.glb", &[("idle", 2.24)][..]),
        ]);
        let src = generate(&input).unwrap();
        assert!(src.contains("let vr_glove_model = Asset.model(\"vr_glove_model.glb\")"));
        assert!(!src.contains("vr_glove_modelClips"));
        assert!(src.contains("let xbot = Asset.model(\"Xbot.glb\")"));
        assert!(src.contains("let xbotClips: XbotClips = {"));
    }

    #[test]
    fn same_shaped_models_share_one_declared_type() {
        // Two models with identical clip fields must NOT declare two
        // same-shaped types (the checker would find the record literals
        // ambiguous) — the second reuses the first's.
        let input = models(&[
            ("xbot.glb", &[("idle", 1.0)][..]),
            ("ybot.glb", &[("idle", 2.0)][..]),
        ]);
        let src = generate(&input).unwrap();
        assert_eq!(src.matches("type XbotClips").count(), 1);
        assert!(!src.contains("type YbotClips"));
        assert!(src.contains("let ybotClips: XbotClips = {"));
    }

    #[test]
    fn same_field_set_in_different_order_still_shares_the_type() {
        // Clip sorting is by ORIGINAL name, so casing can order the same
        // sanitized field set differently per model. The type key must be the
        // sorted SET — emitting two same-shaped types would make every
        // matching literal ambiguous.
        let input = models(&[
            ("abot.glb", &[("Idle", 1.0), ("run", 2.0)][..]),
            ("bbot.glb", &[("idle", 3.0), ("Run", 4.0)][..]),
        ]);
        let src = generate(&input).unwrap();
        assert_eq!(
            src.matches("type ").count(),
            2,
            "Clip + ONE shared model type:\n{src}"
        );
        assert!(src.contains("type AbotClips"));
        assert!(!src.contains("type BbotClips"));
    }

    #[test]
    fn duplicate_clip_names_keep_only_the_first() {
        // Anim.clip plays the FIRST clip with a given name, so a `walk_2`
        // whose .name is still "walk" would be unaddressable — only the
        // first (document-order) duplicate is generated.
        let clips = vec![
            ("walk".to_string(), 1.0),
            ("idle".to_string(), 2.0),
            ("walk".to_string(), 3.0),
        ];
        assert_eq!(duplicate_clip_names(&clips), vec!["walk".to_string()]);
        let input = models(&[("bot.glb", &[("walk", 1.0), ("idle", 2.0), ("walk", 3.0)][..])]);
        let src = generate(&input).unwrap();
        assert!(src.contains("  walk: { name: \"walk\", duration: 1.0 },"));
        assert!(!src.contains("walk_2"));
    }

    #[test]
    fn annotated_clip_records_can_share_the_clip_field_set() {
        // The generated binding annotation disambiguates the outer model
        // record from the inner `Clip` literals even when both record types
        // have exactly `{name, duration}` fields.
        let input = models(&[("weird.glb", &[("name", 1.0), ("duration", 2.0)][..])]);
        let src = generate(&input).unwrap();
        assert!(src.contains("let weird = Asset.model(\"weird.glb\")"));
        assert!(src.contains("type WeirdClips = {"));
        assert!(src.contains("let weirdClips: WeirdClips = {"));
        let parsed = functor_lang::parse(&src).expect("shadowing fields must parse");
        let module = functor_lang::lower(parsed).expect("shadowing fields must lower");
        let diagnostics = functor_lang::check(&module);
        assert!(
            diagnostics.is_empty(),
            "annotated outer record must disambiguate from Clip: {diagnostics:#?}\n{src}"
        );
    }

    /// Hostile names — keyword stems (`if.png` — the lexer reserves
    /// if/then/else/not too), digits, unicode, quotes, commas, even a
    /// newline — must still yield a manifest that PARSES, with the inventory
    /// round-tripping exactly.
    #[test]
    fn hostile_names_still_parse_and_round_trip() {
        let input = local_input(
            &[("2fast.glb", &[("else", 1.0), ("not", 2.0)][..])],
            &["if.png", "then.png", "a, b.png", "qu\"ote.png"],
            &["weird\nname.ogg", "übung.ogg"],
        );
        let src = generate(&input).unwrap();
        assert!(src.contains("let if_ = Asset.texture(\"if.png\")"), "{src}");
        assert!(src.contains("  else_: { name: \"else\", duration: 1.0 },"));
        functor_lang::parse(&src).expect("hostile names must still generate parseable code");
        let mut expected: Vec<String> = [
            "2fast.glb",
            "if.png",
            "then.png",
            "a, b.png",
            "qu\"ote.png",
            "weird\nname.ogg",
            "übung.ogg",
        ]
        .iter()
        .map(|s| s.to_string())
        .collect();
        expected.sort();
        assert_eq!(listed_files(&src).unwrap(), expected);
    }

    /// A sidecar-declared remote asset: the constant is named by the SIDECAR
    /// (`barrel.asset.json` → `barrel`), the constructor gets the URL, and
    /// the inventory lists the sidecar file (the thing with an mtime), not
    /// the URL target.
    #[test]
    fn url_locators_use_the_sidecar_name() {
        let input = ManifestInput {
            models: vec![ModelEntry {
                name: "barrel".to_string(),
                locator: "https://cdn.example.com/meshes/ExplodingBarrel.glb".to_string(),
                clips: vec![("explode".to_string(), 1.5)],
                joints: Vec::new(),
            }],
            files: vec!["barrel.asset.json".to_string()],
            ..Default::default()
        };
        let src = generate(&input).unwrap();
        assert!(src.contains(
            "let barrel = Asset.model(\"https://cdn.example.com/meshes/ExplodingBarrel.glb\")"
        ));
        assert!(src.contains("let barrelClips: BarrelClips = {"));
        assert!(src.contains("  explode: { name: \"explode\", duration: 1.5 },"));
        assert_eq!(listed_files(&src).unwrap(), vec!["barrel.asset.json"]);
    }

    #[test]
    fn old_format_headers_still_count_as_generated() {
        let old = "// GENERATED by functor import — do not edit; rerun after changing models\n\
type Clip = { name: string, duration: float }\n";
        assert!(is_generated(old));
        assert_eq!(listed_files(old), None); // no inventory -> auto-reimport keeps off
        assert!(!is_generated("// my hand-written assets file\n"));
    }

    #[test]
    fn floats_are_plain_literals() {
        assert_eq!(format_float(2.24), "2.24");
        assert_eq!(format_float(0.9667), "0.9667");
        assert_eq!(format_float(2.0), "2.0");
        assert_eq!(format_float(0.0), "0.0");
        // Sub-precision durations round to the fixed grid, never sci-notation.
        assert_eq!(format_float(0.00001), "0.0");
    }

    #[test]
    fn escapes_string_literals() {
        assert_eq!(escape_string("wa\"lk"), "wa\\\"lk");
        assert_eq!(escape_string("a\\b"), "a\\\\b");
        assert_eq!(escape_string("a\nb\tc"), "a\\nb\\tc");
    }
}
