// GENERATED by functor import — do not edit; rerun after changing assets
// files: ["ground.png","hero-atlas.png"]
// Typed asset constants: pass Assets.<name> where an asset goes; clips via Assets.<name>Clips.<clip>

// Textures.
let ground = Asset.texture("ground.png")
let hero_atlas = Asset.texture("hero-atlas.png")
