// GENERATED by functor import — do not edit; rerun after changing assets
// files: ["hit.ogg","shot.ogg"]
// Typed asset constants: pass Assets.<name> where an asset goes; clips via Assets.<name>Clips.<clip>

// Sounds.
let hit = Asset.sound("hit.ogg")
let shot = Asset.sound("shot.ogg")
