name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Separate build job for Rust (will run in parallel)
  build-rust:
    runs-on: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0.x"

      - name: Restore tools
        run: dotnet tool restore

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build Rust
        run: npm run build-rust

      - name: Test Rust
        run: npm run test-rust

  # Separate build job for JavaScript
  build-javascript:
    runs-on: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0.x"

      - name: Restore tools
        run: dotnet tool restore

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1

      - name: Build JS
        run: npm run build-js

      - name: Test JS
        run: npm run test-js
